# Generated by Django 4.1.2 on 2022-10-30 08:47

from django.db import migrations, models
import regular_exam.web.validator


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=20, validators=[regular_exam.web.validator.min_length_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=10, validators=[regular_exam.web.validator.min_length_validator]),
        ),
    ]
