# Generated by Django 4.1.2 on 2022-10-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_car_model_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(verbose_name='Image URL'),
        ),
    ]
