# Generated by Django 4.1.2 on 2022-10-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_car_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('type', 'model')},
        ),
    ]
