# Generated by Django 4.1.2 on 2022-10-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('pk',)},
        ),
    ]
